// Below is how we will be importing the classes and functions from user.js module...
import User from './user.js';
// In the example above, make sure to put ./ or just / and check the console...
const user = new User('Bob', 18);
console.log(user);

// Above is the correct way to import...